### ISSUE TITLE
可以rtsp推流么？或者可以向局域网rtmp服务器推流么？

### ISSUE THREAD

**Issue by Tianluo-Chunlei** [pili-engineering/QNRTC-SampleCode-Video-Basic#8]
可以输出rtsp流么？

可以向局域网rtmp服务器推流么？

试了一下，上面两种方式都不支持。比如一个局域网电脑开启nginx之后，向这个地址推流rtmp://192.168.1.10:1935/live/home，好像推流失败，服务器接不到流。

**Comment by OurEra** [comment]
支持rtmp转推，不支持局域网
https://doc.qnsdk.com/rtn/android/docs/solution_streaming
